spring:
    data:
      mongodb:
          username: admin
          password: password
          host: localhost
          port: 27017
          database: customer
          authentication-database: admin
server:
    port: 8090
